# Generated by Django 2.2.4 on 2020-06-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='care_instructions',
            new_name='description',
        ),
    ]
