# Generated by Django 2.2.4 on 2020-06-19 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='user',
            new_name='user_created',
        ),
    ]
