# Generated by Django 2.2.4 on 2020-06-19 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200619_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobsCreated', to='main.User'),
        ),
    ]
