# Generated by Django 2.2.4 on 2020-06-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hair_color',
            field=models.CharField(default='black', max_length=50),
        ),
    ]
