# Generated by Django 2.2.4 on 2020-06-08 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_hair_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hair_color',
        ),
    ]
